org: kamesan1577
app: crypto-info
service: crypto-info-line-bot

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  architecture: x86_64
  region: ap-northeast-1

functions:
  apiHandler:
    handler: handler.lambda_handler
    events:
      - http:
          path: /webhook
          method: POST
          cors: true
    environment:
      CHANNEL_ACCESS_TOKEN: ${env:CHANNEL_ACCESS_TOKEN}
      CHANNEL_SECRET: ${env:CHANNEL_SECRET}
      COINCHECK_API_KEY: ${env:COINCHECK_API_KEY}
      COINCHECK_SECRET_KEY: ${env:COINCHECK_SECRET_KEY}
      TARGET_GROUP_ID: ${env:TARGET_GROUP_ID}
  cronHandler:
    handler: handler.lambda_handler_cron
    events:
      # Invoke Lambda function every 21:00 Friday
      - schedule: cron(0 21 ? * FRI *)
    environment:
      CHANNEL_ACCESS_TOKEN: ${env:CHANNEL_ACCESS_TOKEN}
      CHANNEL_SECRET: ${env:CHANNEL_SECRET}
      COINCHECK_API_KEY: ${env:COINCHECK_API_KEY}
      COINCHECK_SECRET_KEY: ${env:COINCHECK_SECRET_KEY}
      TARGET_GROUP_ID: ${env:TARGET_GROUP_ID}

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerImage: public.ecr.aws/sam/build-python3.9:latest-x86_64
    dockerizePip: true
    useDownloadCache: true
    useStaticCache: true
    slim: true
